language: node_js
node_js:
  - 'node'

notifications:
  email: false

addons:
  apt:
    packages:
      - zip
      - unzip

before_cache:
  - rm -rf node_modules/.cache

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn build
  - node ./build/locales/locales.js

after_success:
  - zip -rq dist.zip dist
  - res=$(curl -F "file=@dist.zip" https://file.io/?expires=3d)
  - echo $res
  - bash ./build/deploy-www.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in ./build/encrypt.zip.enc -out ./encrypt.zip -d
  - unzip encrypt.zip

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./build/deploy.sh
  on:
    tags: true

env:
  global:
	- secure: CWCrVum9h0996SkQgzGourEYisqdVw/PEl36Ue6D7gdsPGZgOhCzJCJkKH5Uk3fkNF4GXHA0u+8eOJGyMiHXWH1D10+fgYDUSuEEE8/kaUhAvDXymQwJim+tax1johoa5WyitjyWxCXFtfHBcBC6uDI02jkEhhiSUASsXetEFi9I9z4KI2zDLQk8s+y2PKGinusnFGcY1eSKISeDNYP3AZbaieVpgFsiVK+uTLxlmN+l2j7MfnOTZ05VAEQBRGpe0jB9aTm2nSPmXWHvVOb60RhrpI+U2xRGTej+VvoKjIYgz2oSdtC+SQQAtuBAeX+jdpkrK3/Y18n9qCDOjlHZv2RohQEcHzyIOcErF/bwW6ZqYNFOogB2svoiSNCrKPJLCTdl9L0dro+vLSUBxt6F10sTANswe8j9sNVOr9kfsamJRAGDlHItyGA5qC44miO+3ZQyEAXNLJHMctilSrmy3wZqUAOVXl6azJlZrzNt+XVZCrq5FMr+3Fc+p+RhoSheKJi2G8ICFDqqAqOgVxW6nV+3V6yG1arTqX8ArV2wHziFArwotIqdZwWnwdFCfn5kAZpoRefRx45zbj1qJEBO8ByZvwYq3LHr3tsFDenyriMXaNidqMfJlDtAKoyVKdDi/7oWSpzzvupX2ThxVeQF68IJ6v+9Y2U7SUo9LtdRFFk=
	- secure: VtVRiZQIiVVsvVpoMAvYjFyr9ZeDWppMw0FZGeCKAcXdrJxaqe7XuQVPDcWZv1UQq4Gq1B2CbfBMPXrH19iaQ62Dcz+vvbg5euc4Ioix5tul7uawE0pOQdFcopua9BQxwGOyziiVvBXPjTMXEzzyKIRmW/Fg7/eUbVmBcSFVIz0SF284ILG1ocDK3mzpGBWkXalsF/3jmhqnAlWSjMciG4WV5/7QfsaX6AAeUOVFJoIwBmS5/wLbXEOIhQVZxtV3lsHt5B8x3ApNOQHf6PcbeqBdW/ZNH9mXPvJ+R8LtSnylt4JTcSuehhRiTc7RowmXoPjCDEjod1ngmRq/WfRHXqfE1oaQJt8fP//UB7eJRtABW3I/LWiokezn6NJNLa8oz2zwwTcqEoqv+IymY/eycKHJM0HwsCHdXOmCVabvDK165uoX3Z5Zmr7tbBGqNTLfKTZO9/lnXa/zBL7Cy3rtR3C1aihi5uV9cIUxxK1nnUc7Xbs8gpcNRQEi8OfmzCG5taMHXPPw6EGqxBJl9Lgr1wbNZZfbi+Xfnc08wDHm9IrOnXkAO+y8mfdITlo+wO4i8lyxktl4vOcguQQzetfk8M2GM4AdtCt5tgISFGG48QkVWudnQYn3ug6dv7qb2JSo3vuh7fjrU2A1EeuQlPNySfQgJii67++29XhbrFTg6LI=