language: node_js
node_js:
  - 'node'

notifications:
  email: false

addons:
  apt:
    packages:
      - zip
      - unzip

before_cache:
  - rm -rf node_modules/.cache

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn build

after_success:
  - zip -rq dist.zip dist
  - res=$(curl -F "file=@dist.zip" https://file.io/?expires=3d)
  - echo $res

before_deploy:
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in encrypt.zip.enc -out encrypt.zip -d
  - unzip encrypt.zip

deploy:
  provider: script
  skip_cleanup: true
  script: yarn travis:release
  on:
    tags: true
