name: dev

on:
  push:
    branches:
    - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Build
      run: npm run build
    - name: Upload bundles
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
  sync-locale:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Sort
      run: node ./locale/sort-origin.js
    - name: Checkout sync-locale branch
      uses: actions/checkout@v3
      with:
        ref: 'sync-locale'
        path: '_sync_locale_'
    - name: Deploy to dev-locale
      run: |
        rsync -q -av --checksum --progress $GITHUB_WORKSPACE/locale/. $GITHUB_WORKSPACE/_sync_locale_ --exclude .git
        cd ./_sync_locale_
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        GIT_STATUS=$(git status --porcelain)
        if [[ $GIT_STATUS != "" ]]; then
          git add --all .
          git commit -m '[skip ci] sync locale' --quiet --no-verify
          git push
        else
          echo "no content, skip commit"
        fi