name: main

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Build
      run: npm run build
    - name: Upload bundles
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  sync-locale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate files
      run: |
        mkdir ./_SYNC_LOCALE_
        cp -r ./src/locale ./_SYNC_LOCALE_/original
        cp ./transifex.yml ./_SYNC_LOCALE_
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: sync-locale
        folder: _SYNC_LOCALE_
